### ISSUE TITLE
Task doesn't download locales

### ISSUE THREAD

**Issue by elvirdolic** [johannhof/gulp-phraseapp#5]
gulp.task('phraseapp:import', function () { 
phraseapp.download({ accessToken: '0050d305e8d727f9b17a0f0fe5b04c473f968cc607b7c19a682f21b984ccf262', projectID: 'd8edcd56d90af46888852815259911e5' }).pipe(gulp.dest(bases.content + 'i18n')); 
});

![image](https://cloud.githubusercontent.com/assets/17769458/13841838/698ab17e-ec2b-11e5-928f-9fb99c11e6f2.png)

It returns

de-AT.json pt-BR.json instead auf de.json, pt.json 

It worked until we didn't defined the language in phrase-app
![image](https://cloud.githubusercontent.com/assets/17769458/13841868/920a6ba8-ec2b-11e5-91db-855ac48a5a35.png)

Response: 

{
  "message": "Not Found",
  "documentation_url": "https://phraseapp.com/docs/api/v2/"
}

**Comment by elvirdolic** [comment]
This is fixed in the current master branch: url: "/locales/" + locale.id + "/download",

 Can you create a new npm package?

**Comment by johannhof** [comment]
Oh right, forgot, sorry for that.

**Comment by johannhof** [comment]
@elvirdolic done.
